// Default seed content per slug.
// Used only when the document doesn't exist yet in MongoDB.
// Admin can overwrite any field via the CMS.

const defaults = {
  rmc: {
    heroTag:          "SMS INFRA READY MIX CONCRETE",
    heroTitle:        "Premium Ready Mix Concrete Suppliers in Bangalore",
    heroSubtitle:     "SMS Infra delivers high-grade Ready Mix Concrete manufactured with advanced batching plant technology for superior strength, consistency, and on-time delivery across residential, commercial, and infrastructure projects.",
    heroBtnPrimary:   "Request Quote",
    heroBtnSecondary: "View Grades",
    trustItems: [
      { value: "30+",  label: "Years Industry Experience" },
      { value: "IS",   label: "456-2000 Standard Concrete" },
      { value: "24/7", label: "Batch Plant Operations" },
      { value: "100%", label: "Quality Tested Mixes" },
    ],
    aboutTag:   "ABOUT OUR RMC",
    aboutTitle: "Engineered for Superior Structural Performance",
    aboutPara1: "SMS Infra manufactures premium Ready Mix Concrete using a computerised batching plant that ensures precise mix design, consistent water-cement ratios, and optimal aggregate gradation for every pour.",
    aboutPara2: "Our RMC conforms to IS 456-2000 standards and is supplied across Bangalore for residential slabs, commercial foundations, industrial floors, and infrastructure projects.",
    aboutPoints: ["Computerised Batching Plant", "IS 456-2000 Compliant", "On-Time Delivery", "Custom Mix Designs"],
    stats: [
      { value: "M10–M50", label: "Concrete Grades Available" },
      { value: "30+",     label: "Years of Experience" },
      { value: "500+",    label: "Projects Completed" },
      { value: "24/7",    label: "Plant Operations" },
    ],
    servicesHeading: "CONCRETE GRADES",
    servicesTitle:   "Available RMC Grades",
    serviceItems: [
      { title: "M20 Standard",    desc: "Ideal for residential slabs, columns, and general RCC work.", image: "" },
      { title: "M25 Structural",  desc: "High-strength mix for commercial buildings and bridges.", image: "" },
      { title: "M30 Heavy Duty",  desc: "For industrial floors and heavy load-bearing structures.", image: "" },
    ],
    processHeading: "BATCHING PROCESS",
    processTitle:   "How We Produce RMC",
    processSteps: [
      { icon: "🏗️", title: "Mix Design",        desc: "Engineers design the optimal mix ratio for your grade requirement.", image: "" },
      { icon: "⚖️", title: "Batching",           desc: "Computerised weighing of cement, aggregates, water, and admixtures.", image: "" },
      { icon: "🔄", title: "Mixing",             desc: "Drum mixers ensure homogeneous concrete consistency.", image: "" },
      { icon: "🚛", title: "Transit & Delivery", desc: "Transit mixers maintain workability during transport.", image: "" },
      { icon: "✅", title: "Quality Check",      desc: "Slump test and cube test performed before dispatch.", image: "" },
    ],
    featuresHeading: "WHY CHOOSE SMS INFRA RMC",
    featuresTitle:   "Advantages of Our Ready Mix Concrete",
    featuresDesc:    "Our RMC eliminates on-site mixing errors and delivers consistent, high-performance concrete every time.",
    features: [
      { title: "Zero Wastage",        desc: "Precise batching eliminates over-ordering and material waste." },
      { title: "Consistent Quality",  desc: "Every batch is computer-controlled for uniform strength." },
      { title: "Faster Construction", desc: "No site mixing — saves time on every pour." },
      { title: "Custom Mix Designs",  desc: "Grades from M10 to M50 tailored to project needs." },
    ],
    applicationsHeading: "APPLICATIONS",
    applicationsTitle:   "Where Our RMC is Used",
    applications: [
      { label: "Residential Slabs",       image: "" },
      { label: "Commercial Foundations",  image: "" },
      { label: "Industrial Floors",       image: "" },
      { label: "Road & Highway Projects", image: "" },
      { label: "Bridge Construction",     image: "" },
      { label: "Precast Elements",        image: "" },
    ],
    faqs: [
      { question: "What RMC grades do you supply?",   answer: "We supply M10 to M50 grades as per IS 456-2000 for all construction types." },
      { question: "Do you deliver across Bangalore?", answer: "Yes. We deliver across Bangalore and surrounding regions via transit mixers." },
      { question: "How do I place a bulk RMC order?", answer: "Contact our sales team with your grade, volume, and pour schedule." },
    ],
    ctaTag:          "BUILD STRONGER STRUCTURES",
    ctaTitle:        "Looking for Reliable Ready Mix Concrete Suppliers in Bangalore?",
    ctaSubtitle:     "Partner with SMS Infra for consistent, IS-certified RMC delivered on time to your project site.",
    ctaBtnPrimary:   "Request Quote",
    ctaBtnSecondary: "Contact Us",
  },

  aggregates: {
    heroTag:          "Premium Blue Metal Aggregates",
    heroTitle:        "Premium Construction Aggregates Suppliers in Bangalore",
    heroSubtitle:     "SMS Infra delivers high-strength construction aggregates manufactured using advanced VSI crushing technology for superior concrete durability, structural stability, and long-lasting performance.",
    heroBtnPrimary:   "Request Quote",
    heroBtnSecondary: "View Sizes",
    trustItems: [
      { value: "30+",  label: "Years Industry Experience" },
      { value: "IS",   label: "383-2016 Standard Materials" },
      { value: "24/7", label: "Reliable Bulk Supply" },
      { value: "100%", label: "Quality Tested Aggregates" },
    ],
    aboutTag:   "ABOUT OUR AGGREGATES",
    aboutTitle: "Engineered for Superior Construction Performance",
    aboutPara1: "SMS Infra manufactures premium-quality construction aggregates using advanced three-stage crushing and VSI shaping technology for superior particle consistency and high compression strength.",
    aboutPara2: "Our aggregates conform to IS 383-2016 standards and are widely used across residential, commercial, RCC, and infrastructure projects throughout Bangalore.",
    aboutPoints: ["Cubical Aggregate Formation", "Reduced Flaky Particles", "Better Concrete Durability", "Superior Load Distribution"],
    stats: [
      { value: "4",    label: "Aggregate Sizes (6–40MM)" },
      { value: "30+",  label: "Years of Experience" },
      { value: "IS",   label: "383-2016 Certified" },
      { value: "100%", label: "VSI Cubical Shaped" },
    ],
    servicesHeading: "PRODUCT RANGE",
    servicesTitle:   "Available Aggregate Sizes",
    serviceItems: [
      { title: "6MM Fine Grade",      desc: "For tile bedding, fine concrete, and precast products.", image: "" },
      { title: "12MM RCC Aggregates", desc: "For RCC works, slabs, beams, and columns.", image: "" },
      { title: "20MM Structural",     desc: "For commercial buildings and heavy foundations.", image: "" },
      { title: "40MM Infrastructure", desc: "For road works, mass concreting, and drainage.", image: "" },
    ],
    processHeading: "MANUFACTURING PROCESS",
    processTitle:   "Advanced 3-Stage Crushing Technology",
    processSteps: [
      { icon: "⛏️", title: "Raw Stone Sourcing", desc: "Premium raw stones from trusted quarries.", image: "" },
      { icon: "🔨", title: "Jaw Crushing",        desc: "Primary crushing for optimised material sizing.", image: "" },
      { icon: "🔩", title: "Cone Crushing",       desc: "Secondary crushing for precise aggregate formation.", image: "" },
      { icon: "🔄", title: "VSI Shaping",         desc: "Cubical particles with minimal flakiness.", image: "" },
      { icon: "✅", title: "Quality Testing",     desc: "Strict IS-standard testing for gradation and strength.", image: "" },
    ],
    featuresHeading: "WHY CUBICAL AGGREGATES",
    featuresTitle:   "Advantages of VSI-Shaped Aggregates",
    featuresDesc:    "Our VSI shaping process produces cubical aggregates with superior bonding properties and reduced segregation.",
    features: [
      { title: "Improved Concrete Strength",  desc: "Cubical shape ensures maximum contact surface between particles." },
      { title: "Reduced Voids & Segregation", desc: "Uniform gradation prevents segregation in fresh concrete." },
      { title: "Better Workability",          desc: "Consistent shape improves concrete flow and placement." },
      { title: "Reduced Cement Consumption",  desc: "Optimal gradation reduces paste requirement by up to 10%." },
    ],
    applicationsHeading: "APPLICATIONS",
    applicationsTitle:   "Construction Applications",
    applications: [
      { label: "Residential Buildings",   image: "" },
      { label: "Commercial Projects",     image: "" },
      { label: "Road & Highway Projects", image: "" },
      { label: "Industrial Foundations",  image: "" },
      { label: "Infrastructure Projects", image: "" },
      { label: "RCC Structures",          image: "" },
    ],
    faqs: [
      { question: "What aggregate sizes are available?",   answer: "We supply 6MM, 12MM, 20MM, and 40MM blue metal aggregates." },
      { question: "Are your aggregates IS certified?",     answer: "Yes, conforming to IS 383-2016." },
      { question: "Why are VSI-shaped aggregates better?", answer: "Cubical shape reduces flaky particles, improving concrete strength." },
    ],
    ctaTag:          "BUILD STRONGER STRUCTURES",
    ctaTitle:        "Looking for Premium Aggregates Suppliers in Bangalore?",
    ctaSubtitle:     "Partner with SMS Infra for high-performance blue metal aggregates engineered for superior strength and durability.",
    ctaBtnPrimary:   "Request Quote",
    ctaBtnSecondary: "Contact Us",
  },

  earthmovers: {
    heroTag:          "SMS INFRA EARTHMOVERS",
    heroTitle:        "Professional Earthmoving & Excavation Services in Bangalore",
    heroSubtitle:     "SMS Infra provides reliable earthmoving and excavation services using modern JCB, excavator, and compactor machinery for site preparation, grading, trenching, and infrastructure projects.",
    heroBtnPrimary:   "Request Quote",
    heroBtnSecondary: "View Equipment",
    trustItems: [
      { value: "30+",  label: "Years Industry Experience" },
      { value: "50+",  label: "Projects Completed" },
      { value: "24/7", label: "Equipment Availability" },
      { value: "100%", label: "Operator Trained Staff" },
    ],
    aboutTag:   "ABOUT EARTHMOVERS",
    aboutTitle: "Precision Earthmoving for Every Site",
    aboutPara1: "SMS Infra operates a modern fleet of excavators, JCBs, motor graders, and compactors for reliable earthmoving services across Bangalore and surrounding regions.",
    aboutPara2: "Our skilled operators and well-maintained machinery ensure projects are completed safely, on schedule, and within budget.",
    aboutPoints: ["Modern Fleet of Machines", "Trained & Certified Operators", "On-Time Project Delivery", "Competitive Hiring Rates"],
    stats: [
      { value: "30+",  label: "Years of Experience" },
      { value: "50+",  label: "Active Machines" },
      { value: "200+", label: "Projects Completed" },
      { value: "24/7", label: "Equipment Support" },
    ],
    servicesHeading: "OUR SERVICES",
    servicesTitle:   "Earthmoving Services We Offer",
    serviceItems: [
      { title: "Excavation",      desc: "Site excavation for basements, foundations, and trenches.", image: "" },
      { title: "Site Grading",    desc: "Land levelling and grading for construction-ready surfaces.", image: "" },
      { title: "Rock Breaking",   desc: "Hydraulic breaker services for hard rock excavation.", image: "" },
      { title: "Soil Compaction", desc: "Compactor services for road sub-base and fill compaction.", image: "" },
    ],
    processHeading: "HOW WE WORK",
    processTitle:   "Our Project Execution Process",
    processSteps: [
      { icon: "📋", title: "Site Inspection",  desc: "Our engineers assess the site before mobilisation.", image: "" },
      { icon: "📐", title: "Terrain Analysis", desc: "Soil type and terrain analysis for machine selection.", image: "" },
      { icon: "🚧", title: "Mobilisation",     desc: "Equipment transported and deployed on schedule.", image: "" },
      { icon: "⚙️", title: "Execution",        desc: "Systematic earthmoving with daily progress tracking.", image: "" },
      { icon: "✅", title: "Site Handover",    desc: "Final survey and site handover documentation.", image: "" },
    ],
    featuresHeading: "WHY SMS INFRA EARTHMOVERS",
    featuresTitle:   "Why Choose Our Earthmoving Services",
    featuresDesc:    "We combine modern machinery, skilled operators, and project management expertise to deliver reliable earthmoving solutions.",
    features: [
      { title: "Modern Machinery",  desc: "Well-maintained JCBs, excavators, and graders for every job." },
      { title: "Skilled Operators", desc: "All operators are trained, certified, and safety-compliant." },
      { title: "On-Time Delivery",  desc: "We adhere strictly to project timelines." },
      { title: "Safety First",      desc: "All operations follow IS safety standards and protocols." },
    ],
    applicationsHeading: "APPLICATIONS",
    applicationsTitle:   "Where We Operate",
    applications: [
      { label: "Residential Plots",       image: "" },
      { label: "Commercial Sites",        image: "" },
      { label: "Road & Highway Projects", image: "" },
      { label: "Industrial Plants",       image: "" },
      { label: "Infrastructure Works",    image: "" },
      { label: "Drainage & Trenching",    image: "" },
    ],
    faqs: [
      { question: "What machines do you operate?",          answer: "JCBs, excavators, motor graders, and soil compactors." },
      { question: "Do you take short-term hire?",           answer: "Yes, we offer daily, weekly, and monthly hiring." },
      { question: "Do you serve areas outside Bangalore?",  answer: "Yes, we operate across Bangalore and nearby districts." },
    ],
    ctaTag:          "GET YOUR SITE READY",
    ctaTitle:        "Need Professional Earthmoving Services in Bangalore?",
    ctaSubtitle:     "Contact SMS Infra for reliable, on-schedule earthmoving and excavation services at competitive rates.",
    ctaBtnPrimary:   "Request Quote",
    ctaBtnSecondary: "Contact Us",
  },

  msand: {
    heroTag:          "SMS INFRA M SAND & P SAND",
    heroTitle:        "Premium M Sand & P Sand Suppliers in Bangalore",
    heroSubtitle:     "SMS Infra supplies high-quality Manufactured Sand (M Sand) and Plastering Sand (P Sand) manufactured using advanced VSI technology — a superior, eco-friendly alternative to river sand.",
    heroBtnPrimary:   "Request Quote",
    heroBtnSecondary: "Compare Grades",
    trustItems: [
      { value: "IS",   label: "2116 & 383 Certified" },
      { value: "100%", label: "River Sand Alternative" },
      { value: "24/7", label: "Bulk Supply Available" },
      { value: "30+",  label: "Years of Experience" },
    ],
    aboutTag:   "ABOUT M SAND & P SAND",
    aboutTitle: "Superior Alternative to Natural River Sand",
    aboutPara1: "SMS Infra manufactures M Sand (Masonry Sand) and P Sand (Plastering Sand) from crushed granite using advanced VSI technology, ensuring consistent particle shape, size, and gradation.",
    aboutPara2: "Our sand conforms to IS 2116 and IS 383 standards and is widely used for concrete works, masonry, and internal/external plastering across Bangalore.",
    aboutPoints: ["Consistent Gradation", "Zero Organic Impurities", "IS Certified", "Eco-Friendly Production"],
    stats: [
      { value: "2",   label: "Grades: M Sand & P Sand" },
      { value: "IS",  label: "2116 & 383 Certified" },
      { value: "0%",  label: "Organic Impurities" },
      { value: "30+", label: "Years of Experience" },
    ],
    servicesHeading: "OUR PRODUCTS",
    servicesTitle:   "M Sand & P Sand Grades",
    serviceItems: [
      { title: "M Sand (Concrete Sand)", desc: "For RCC, concrete, foundations, and structural works.", image: "" },
      { title: "P Sand (Plaster Sand)",  desc: "Finely graded sand for internal and external plastering.", image: "" },
    ],
    processHeading: "MANUFACTURING PROCESS",
    processTitle:   "How M Sand & P Sand are Made",
    processSteps: [
      { icon: "⛏️", title: "Granite Sourcing", desc: "High-quality granite rocks sourced from certified quarries.", image: "" },
      { icon: "🔨", title: "Primary Crushing", desc: "Jaw crusher reduces granite to workable aggregate size.", image: "" },
      { icon: "🔩", title: "VSI Shaping",      desc: "VSI crusher produces cubical, well-graded sand particles.", image: "" },
      { icon: "🔍", title: "Screening",        desc: "Precise vibrating screens separate M Sand and P Sand grades.", image: "" },
      { icon: "✅", title: "Quality Testing",  desc: "Gradation, silt content, and fineness modulus tested per IS.", image: "" },
    ],
    comparisonHeading:    "WHY M-SAND",
    comparisonTitle:      "M Sand vs River Sand",
    comparisonLeftTitle:  "River Sand (Traditional)",
    comparisonLeftPoints: [
      "Variable particle shape and size",
      "Contains organic impurities and silt",
      "Environmentally damaging to riverbeds",
      "Increasingly scarce and expensive",
      "Inconsistent gradation",
    ],
    comparisonRightTitle:  "SMS Infra M Sand",
    comparisonRightPoints: [
      "Consistent cubical particle shape",
      "Zero organic impurities — IS certified",
      "Eco-friendly — manufactured from granite",
      "Readily available in bulk",
      "Precise IS 383 gradation",
    ],
    featuresHeading: "BENEFITS OF M SAND",
    featuresTitle:   "Why M Sand is Better for Construction",
    featuresDesc:    "M Sand eliminates the inconsistency and environmental damage of river sand while delivering superior concrete and masonry performance.",
    features: [
      { title: "Zero Organic Impurities",  desc: "Manufactured process ensures no clay, silt, or organic matter." },
      { title: "Consistent Gradation",     desc: "Precise screening delivers uniform fineness modulus every batch." },
      { title: "Higher Concrete Strength", desc: "Cubical shape ensures better interlocking with cement paste." },
      { title: "Eco-Friendly",             desc: "Reduces dependence on river sand, protecting natural ecosystems." },
    ],
    applicationsHeading: "APPLICATIONS",
    applicationsTitle:   "Where M Sand & P Sand are Used",
    applications: [
      { label: "RCC Concrete Works",  image: "" },
      { label: "Masonry & Brickwork", image: "" },
      { label: "Internal Plastering", image: "" },
      { label: "External Plastering", image: "" },
      { label: "Floor Screeding",     image: "" },
      { label: "Precast Elements",    image: "" },
    ],
    faqs: [
      { question: "What is the difference between M Sand and P Sand?", answer: "M Sand is coarser and used for concrete/RCC, while P Sand is finer and used for plastering." },
      { question: "Is M Sand IS certified?",                            answer: "Yes, our M Sand conforms to IS 383-2016 and P Sand to IS 2116-1980." },
      { question: "Is M Sand a suitable river sand replacement?",       answer: "Yes. M Sand matches or exceeds river sand performance while being eco-friendly." },
    ],
    ctaTag:          "BUILD CLEANER & STRONGER",
    ctaTitle:        "Looking for M Sand & P Sand Suppliers in Bangalore?",
    ctaSubtitle:     "Contact SMS Infra for IS-certified M Sand and P Sand delivered in bulk across Bangalore.",
    ctaBtnPrimary:   "Request Quote",
    ctaBtnSecondary: "Contact Us",
  },

  "solid-blocks": {
    heroTag:          "SMS INFRA SOLID BLOCKS",
    heroTitle:        "Premium Solid Concrete Blocks Manufacturers in Bangalore",
    heroSubtitle:     "SMS Infra manufactures high-strength solid concrete blocks and hollow blocks engineered for superior load-bearing performance, thermal insulation, and structural integrity across residential and commercial construction.",
    heroBtnPrimary:   "Request Quote",
    heroBtnSecondary: "View Sizes",
    trustItems: [
      { value: "IS",   label: "2185 Standard Blocks" },
      { value: "30+",  label: "Years Industry Experience" },
      { value: "100%", label: "Machine Moulded" },
      { value: "24/7", label: "Bulk Supply Available" },
    ],
    aboutTag:   "ABOUT SOLID BLOCKS",
    aboutTitle: "Machine-Moulded for Structural Precision",
    aboutPara1: "SMS Infra manufactures solid and hollow concrete blocks using automated block-making machines with precise cement-aggregate ratios for consistent strength and dimensional accuracy.",
    aboutPara2: "Our blocks conform to IS 2185 standards and are suitable for load-bearing walls, boundary walls, and partition walls in residential, commercial, and industrial construction.",
    aboutPoints: ["IS 2185 Certified", "Machine Moulded Precision", "Superior Load-Bearing Capacity", "Thermal & Sound Insulation"],
    stats: [
      { value: "IS",   label: "2185 Certified Blocks" },
      { value: "30+",  label: "Years of Experience" },
      { value: "100%", label: "Machine Moulded" },
      { value: "24/7", label: "Bulk Supply" },
    ],
    servicesHeading: "PRODUCT RANGE",
    servicesTitle:   "Block Sizes & Types Available",
    serviceItems: [
      { title: "Solid Blocks 4\"", desc: "Lightweight partition walls and non-load bearing applications.", image: "" },
      { title: "Solid Blocks 6\"", desc: "Standard load-bearing walls for residential construction.", image: "" },
      { title: "Solid Blocks 8\"", desc: "Heavy-duty walls for commercial and industrial structures.", image: "" },
      { title: "Hollow Blocks",    desc: "Lighter alternative with thermal insulation properties.", image: "" },
    ],
    comparisonHeading:    "SOLID BLOCKS VS BRICKS",
    comparisonTitle:      "Solid Blocks vs Traditional Bricks",
    comparisonLeftTitle:  "Traditional Clay Bricks",
    comparisonLeftPoints: [
      "Irregular dimensions — plaster waste",
      "Lower compressive strength",
      "Higher mortar consumption",
      "Environmentally damaging (kiln firing)",
      "Slower construction pace",
    ],
    comparisonRightTitle:  "SMS Infra Solid Blocks",
    comparisonRightPoints: [
      "Precise dimensions — minimal plaster",
      "Higher compressive strength (IS 2185)",
      "30–40% less mortar required",
      "Eco-friendly — no kiln burning",
      "Faster masonry construction",
    ],
    featuresHeading: "WHY SOLID BLOCKS",
    featuresTitle:   "Advantages Over Traditional Bricks",
    featuresDesc:    "Solid blocks offer superior structural performance, faster construction, and lower long-term costs compared to traditional clay bricks.",
    features: [
      { title: "Higher Strength",         desc: "Machine-compacted blocks deliver consistent compressive strength." },
      { title: "Faster Construction",     desc: "Larger block size means fewer courses and faster wall completion." },
      { title: "Less Mortar",             desc: "Uniform dimensions reduce mortar joint wastage." },
      { title: "Sound & Heat Insulation", desc: "Dense concrete matrix reduces heat and noise transmission." },
    ],
    applicationsHeading: "APPLICATIONS",
    applicationsTitle:   "Where Solid Blocks Are Used",
    applications: [
      { label: "Load-Bearing Walls",    image: "" },
      { label: "Boundary Walls",        image: "" },
      { label: "Partition Walls",       image: "" },
      { label: "Commercial Buildings",  image: "" },
      { label: "Industrial Structures", image: "" },
      { label: "Compound Walls",        image: "" },
    ],
    faqs: [
      { question: "Are your blocks IS certified?",     answer: "Yes, all blocks conform to IS 2185-2005 for compressive strength and dimensions." },
      { question: "What sizes do you manufacture?",    answer: "We manufacture 4\", 6\", and 8\" solid blocks and standard hollow blocks." },
      { question: "Do you supply for large projects?", answer: "Yes, we accept bulk orders for residential, commercial, and industrial projects." },
    ],
    ctaTag:          "BUILD STRONGER WALLS",
    ctaTitle:        "Looking for Solid Block Manufacturers in Bangalore?",
    ctaSubtitle:     "Choose SMS Infra solid blocks for consistent strength, precise dimensions, and on-time bulk delivery.",
    ctaBtnPrimary:   "Request Quote",
    ctaBtnSecondary: "Contact Us",
  },

  builders: {
    // ── Hero ────────────────────────────────────────────────────────────────
    heroTag:          "Launching Soon — Countdown Active",
    heroTitle:        "Building Tomorrow's Bangalore",
    heroSubtitle:     "A new era of construction begins — premium residential, commercial, and EPC infrastructure, launching very soon.",
    heroBtnPrimary:   "Get Early Consultation",
    heroBtnSecondary: "Get Notified",
    heroBgImage:      "/builders/builders-hero.png",

    // ── Launching Soon section ───────────────────────────────────────────────
    launchDate:          "2027-01-01T00:00:00",
    launchingTag:        "Future Infrastructure Division",
    launchingHeading:    "Building Tomorrow's Infrastructure",
    launchingCardHeader: "Division In Progress",
    launchingCardBody:   "Our Builders & Infrastructure division is in final stages of development. Residential villas, commercial complexes, and end-to-end EPC solutions — all launching very soon across Bangalore and Karnataka.",
    launchProgressBars: [
      { label: "Infrastructure Setup", pct: 88 },
      { label: "Team Onboarding",      pct: 74 },
      { label: "Project Pipeline",     pct: 61 },
      { label: "Tech Integration",     pct: 45 },
    ],
    launchMilestones:    ["Planning", "Setup", "Launch", "Scale"],
    notifyCardHeading:   "Get Launch Updates",
    notifyCardSubtext:   "Be the first to know when we go live.",

    // ── Popup ────────────────────────────────────────────────────────────────
    popupBadge:    "Launching Soon",
    popupTitle1:   "Something Big",
    popupTitle2:   "Is Coming",
    popupSubtitle: "Premium construction & infrastructure solutions for Bangalore. Be the first to know.",
    popupFeatures: ["Residential Villas", "Commercial Complexes", "EPC Solutions"],

    // ── Services ─────────────────────────────────────────────────────────────
    servicesHeading: "Upcoming Services",
    servicesTitle:   "Future Construction & Infrastructure Solutions",
    serviceItems: [
      { title: "Residential Construction", desc: "Modern residential solutions — villas, apartments, gated communities — built with premium materials, smart layouts, and on-time delivery.", image: "/builders/residential-project.png" },
      { title: "Commercial Projects",      desc: "Office towers, retail spaces, industrial facilities, and warehouses built for scale, durability, and business performance.", image: "/builders/commercial-project.png" },
      { title: "EPC Solutions",            desc: "Engineering, Procurement & Construction services for large-scale infrastructure — from concept to final handover.", image: "/builders/epc-project.png" },
    ],

    // ── Why Us / Features ─────────────────────────────────────────────────
    featuresHeading: "Why Choose Us",
    featuresTitle:   "Future-Ready Construction Excellence",
    featuresDesc:    "",
    features: [
      { title: "Quality-First Approach", desc: "Premium materials, structural integrity, and uncompromising construction standards on every project." },
      { title: "Fast Execution",          desc: "Timeline-driven project management with milestone tracking and transparent delivery schedules." },
      { title: "End-to-End Planning",     desc: "Integrated workflow from concept design to final handover — one partner, zero gaps." },
      { title: "Scalable Solutions",      desc: "Future-ready capabilities for projects of any scale — residential plots to industrial complexes." },
    ],

    // ── Roadmap / Process ─────────────────────────────────────────────────
    processHeading: "Growth Roadmap",
    processTitle:   "Future Infrastructure Expansion Plan",
    processSteps: [
      { icon: "", title: "Residential Projects",     desc: "", image: "" },
      { icon: "", title: "Commercial Infrastructure", desc: "", image: "" },
      { icon: "", title: "EPC & Industrial",          desc: "", image: "" },
      { icon: "", title: "Smart Cities",              desc: "", image: "" },
    ],

    // ── FAQs ──────────────────────────────────────────────────────────────
    faqs: [
      { question: "When will the Builders & Infrastructure division launch?", answer: "Our division is in the final stages of setup and will officially launch soon with full residential, commercial, and EPC construction services." },
      { question: "What construction services will be offered?",              answer: "We will offer residential construction, commercial infrastructure development, and complete end-to-end EPC solutions for industrial and infrastructure projects." },
      { question: "Will EPC services be available for industrial projects?",  answer: "Yes — our EPC division will cover industrial infrastructure, large-scale construction, and complete project lifecycle management." },
      { question: "Do you provide residential construction in Bangalore?",    answer: "Yes. Our residential division will focus primarily on Bangalore and the broader Karnataka region." },
    ],

    // ── CTA ───────────────────────────────────────────────────────────────
    ctaTag:          "Future Construction Partnerships",
    ctaTitle:        "Planning a Future Construction Project?",
    ctaSubtitle:     "Connect with our team today to discuss upcoming residential, commercial, and infrastructure development requirements.",
    ctaBtnPrimary:   "Contact Team",
    ctaBtnSecondary: "Get Notified",
  },
};

export default defaults;